# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GjS9ypvny4x5IZKwI_ze4Q4BUl1PHC8V
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
# Load the dataset from a CSV file
df = pd.read_csv("/content/StudentsPerformance.csv")

# View the first 5 rows of the dataset
print(df.head())

# 1. Scatter plot of math score vs. reading score with color-coded gender
sns.scatterplot(x="math score", y="reading score", data=df, hue="gender")
plt.show()

# 2. Histogram of writing scores by gender
sns.histplot(x="writing score", data=df, hue="gender", multiple="stack")
plt.show()

# 3. Violin plot of race/ethnicity vs. math score
sns.violinplot(x="race/ethnicity", y="math score", data=df)
plt.show()

# 4. Correlation Plot / Heat map
sns.heatmap(df.corr(), cmap="coolwarm", annot=True)
plt.title("Correlation Matrix")
plt.show()

# 5. Stacked bar chart of lunch type vs. pass/fail status by race/ethnicity
sns.boxplot(data=df, x="race/ethnicity", y="math score")
plt.title("Math Score by Race/Ethnicity")
plt.xlabel("Race/Ethnicity")
plt.ylabel("Math Score")
plt.show()